-- MySQL Script generated by MySQL Workbench
-- Thu Jun 25 13:37:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema transferapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transferapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transferapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `transferapp` ;

-- -----------------------------------------------------
-- Table `transferapp`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferapp`.`user_account` (
  `id` BIGINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `money_amount` DOUBLE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_hl02wv5hym99ys465woijmfib` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferapp`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferapp`.`bank_account` (
  `id` BIGINT NOT NULL,
  `account_iban` VARCHAR(255) NOT NULL,
  `account_name` VARCHAR(255) NOT NULL,
  `useraccount_email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_j85d2ehxmc9smyxrwhvldrbm4` (`account_iban` ASC) VISIBLE,
  INDEX `FKgj2i9h5binos42o4ousao7fdo` (`useraccount_email` ASC) VISIBLE,
  CONSTRAINT `FKgj2i9h5binos42o4ousao7fdo`
    FOREIGN KEY (`useraccount_email`)
    REFERENCES `transferapp`.`user_account` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferapp`.`relation_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferapp`.`relation_email` (
  `id` BIGINT NOT NULL,
  `relative_email` VARCHAR(255) NOT NULL,
  `useraccount_email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8p09558qtkla38vv628qocobn` (`useraccount_email` ASC) VISIBLE,
  CONSTRAINT `FK8p09558qtkla38vv628qocobn`
    FOREIGN KEY (`useraccount_email`)
    REFERENCES `transferapp`.`user_account` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferapp`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferapp`.`transaction` (
  `id` BIGINT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `date` DATETIME(6) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `is_receiving` BIT(1) NOT NULL,
  `perceive_amount_for_app` DOUBLE NOT NULL,
  `relative_email` VARCHAR(255) NOT NULL,
  `useraccount_email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKtq08defv71f1rk5lyh9733ke2` (`useraccount_email` ASC) VISIBLE,
  CONSTRAINT `FKtq08defv71f1rk5lyh9733ke2`
    FOREIGN KEY (`useraccount_email`)
    REFERENCES `transferapp`.`user_account` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
